blank_issues_enabled: false
contact_links:
  - name: 📚 Project Documentation
    url: https://github.com/YOUR_USERNAME/YOUR_REPO/blob/main/README.md
    about: Check the project documentation and user guide first
  - name: 💬 Discussion Forum
    url: https://github.com/YOUR_USERNAME/YOUR_REPO/discussions
    about: Ask questions and discuss features with the community
  - name: 🔧 Configuration Help
    url: https://github.com/YOUR_USERNAME/YOUR_REPO/blob/main/CLAUDE.md
    about: Get help with project configuration and setup