name: ðŸ”´ Control Systems - Stability Issue
description: Report stability problems in control systems (CRITICAL)
title: "[STABILITY] "
labels: ["bug", "stability", "critical", "control-systems"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## ðŸ”´ Critical Stability Issue
        Use this template for stability violations, Lyapunov analysis failures, or control system instability.
        **Response Time**: < 4 hours

  - type: dropdown
    id: stability_type
    attributes:
      label: Stability Issue Type
      description: Select the type of stability problem
      options:
        - Lyapunov Stability Violation
        - Reaching Phase Instability
        - Sliding Phase Instability
        - Excessive Chattering
        - Parameter Adaptation Divergence
        - Estimation Error Accumulation
        - Learning Rate Sensitivity
      default: 0
    validations:
      required: true

  - type: dropdown
    id: controller_type
    attributes:
      label: Controller Type
      description: Which controller is experiencing stability issues?
      options:
        - Classical SMC
        - Super-Twisting SMC
        - Adaptive SMC
        - Hybrid Adaptive STA-SMC
        - Swing-up SMC
        - MPC Controller
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: stability_analysis
    attributes:
      label: Stability Analysis Results
      description: Provide Lyapunov analysis results, eigenvalue analysis, or simulation evidence
      placeholder: |
        - Lyapunov function: V(x) = ...
        - Derivative analysis: dV/dt = ...
        - Eigenvalues: Î» = [...]
        - Simulation results: ...
    validations:
      required: true

  - type: textarea
    id: control_gains
    attributes:
      label: Current Control Gains
      description: Provide the control gains being used
      placeholder: |
        K = [K1, K2, K3, K4, K5, K6] = [10.0, 5.0, 8.0, 3.0, 15.0, 2.0]
        c = [c1, c2, c3, c4] = [1.0, 1.0, 1.0, 1.0]
        Other parameters: ...
    validations:
      required: true

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Reproduction Steps
      description: Detailed steps to reproduce the stability issue
      placeholder: |
        1. Configure controller with gains: ...
        2. Run simulation with: python simulate.py --ctrl classical_smc --plot
        3. Observe instability at time: ...
        4. Analysis shows: ...
    validations:
      required: true

  - type: textarea
    id: system_info
    attributes:
      label: System Configuration
      description: Provide system and configuration details
      placeholder: |
        - Plant model: Simplified/Full/LowRank
        - Initial conditions: [Î¸1, Î¸2, Î¸1_dot, Î¸2_dot] = [...]
        - Simulation time: ...
        - Time step: dt = ...
        - Python version: ...
    validations:
      required: true

  - type: checkboxes
    id: safety_impact
    attributes:
      label: Safety Impact Assessment
      description: Check all that apply
      options:
        - label: System instability observed
        - label: Hardware damage potential
        - label: Safety constraints violated
        - label: Real-time requirements not met
        - label: Complete control failure

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any additional information, logs, plots, or context
      placeholder: Add any other context about the stability issue here...