#======================================================================================\\\
#======================= tests/test_plant/core/test_dynamics.py =======================\\\
#======================================================================================\\\

"""
This file is auto‑generated by refactor_tests.sh.
It combines the following original test modules: test_full_dynamics.py, test_model_comparison.py, test_dynamics_ill_conditioned.py, test_linalg_fix.py, test_disturbance_boundary.py.
Each section is delimited by BEGIN/END markers.
"""

# BEGIN: test_full_dynamics.py
#tests/test_full_dynamics====================================================================\\\

import numpy as np
import pytest

# Import only the components that exist in the project.  CostFunction, PSOConfig, and
# PSOBounds are not available in src.config, so they are no longer imported here.
from src.config import load_config, PhysicsConfig
from src.plant.models.full.dynamics import FullDIPDynamics
from src.core.dynamics import step_rk4_numba
from src.utils.config_compatibility import wrap_physics_config

@pytest.fixture(scope="module")
def full_dynamics_model():
    """Provides a reusable instance of the full dynamics model from the project config."""
    cfg = load_config("config.yaml", allow_unknown=True)
    # Use configuration compatibility wrapper to handle different config types
    physics_config = wrap_physics_config(cfg.physics)
    return FullDIPDynamics(config=physics_config)


def test_full_inertia_matrix_shape_and_symmetry(full_dynamics_model):
    """
    The inertia matrix H must be 3x3 and symmetric.
    """
    state = np.array([0.0, np.pi / 4, np.pi / 6, 0, 0, 0])  # A non-trivial state
    H, _, _ = full_dynamics_model.get_physics_matrices(state)

    assert H.shape == (3, 3), f"Expected inertia matrix H to have shape 3x3, but got {H.shape}"
    assert np.allclose(H, H.T), "Inertia matrix H must be symmetric"


def test_full_dynamics_computation(full_dynamics_model):
    """
    The dynamics method should execute and output a valid 6-element derivative vector.
    """
    state = np.array([0.0, 0.1, 0.1, 0.2, 0.5, 0.3])
    control_input = 10.0

    result = full_dynamics_model.compute_dynamics(state, np.array([control_input]))
    derivative = result.state_derivative

    assert derivative.shape == (6,), f"Expected derivative shape (6,), but got {derivative.shape}"
    assert np.all(np.isfinite(derivative)), "Derivative contains non-finite (NaN or Inf) values"


def test_passivity_verification(full_dynamics_model):
    """
    Verifies that the system's energy does not increase without external power input
    when friction (dissipation) is removed. This test is flawed in the original code,
    as FullDIPDynamics does not have a 'verify_passivity' method. We will test energy
    conservation instead.
    """
    # Create a frictionless version of the model for a pure energy conservation test
    params_dict = vars(full_dynamics_model.config).copy()
    params_dict['cart_viscous_friction'] = 0.0
    params_dict['cart_coulomb_friction'] = 0.0
    params_dict['joint1_friction'] = 0.0
    params_dict['joint2_friction'] = 0.0
    model_no_friction = FullDIPDynamics(config=params_dict)

    state = np.array([0.0, 0.1, 0.05, 0.1, 0.2, 0.3])
    initial_energy = model_no_friction.compute_energy_analysis(state)['total_energy']

    # Take one step with zero input force (manual Euler integration)
    dt = 0.01
    result = model_no_friction.compute_dynamics(state, np.array([0.0]))
    next_state = state + dt * result.state_derivative
    final_energy = model_no_friction.compute_energy_analysis(next_state)['total_energy']
    
    # Energy should not increase (within a small tolerance for numerical error)
    # Allow a small tolerance due to numerical integration error.  Euler integration
    # has larger errors than RK4, so use 1e-3 tolerance.
    assert final_energy <= initial_energy + 1e-3, (
        f"Passivity check failed: The model's energy increased without input. "
        f"Initial: {initial_energy:.6f}, Final: {final_energy:.6f}"
    )


def test_singularity_check(full_dynamics_model):
    """
    Tests singularity detection for both a standard non-singular case and a
    numerically induced singular case by checking the determinant of the inertia matrix.
    """
    # 1. A standard configuration should not be singular.
    H, _, _ = full_dynamics_model.get_physics_matrices(np.array([0, 0, np.pi, 0, 0, 0]))
    assert np.linalg.det(H) != 0, "A standard configuration was incorrectly flagged as singular."

    # 2. Induce a singularity by creating a model where the second pendulum has
    #    near-zero mass and inertia. This makes the inertia matrix ill-conditioned
    #    (numerically singular) without violating model parameter validation.
    singular_params_dict = vars(full_dynamics_model.config).copy()
    singular_params_dict['pendulum2_mass'] = 1e-12
    singular_params_dict['pendulum2_inertia'] = 1e-12
    model_singular = FullDIPDynamics(config=singular_params_dict)

    H_singular, _, _ = model_singular.get_physics_matrices(np.array([0, 0, np.pi, 0, 0, 0]))
    assert abs(np.linalg.det(H_singular)) < 1e-9, "A known singular configuration was not detected."

@pytest.mark.skip(reason="Test uses deprecated FullDIPParams and step_rk4_numba from old API - requires refactoring")
def test_step_returns_nan_on_singular_params():
    p = FullDIPParams(  # noqa: F821 - conditional import or test mock
        cart_mass=1.0,
        pendulum1_mass=1.0,
        pendulum2_mass=1e-12,     # force singularity
        pendulum1_length=1.0,
        pendulum2_length=1.0,
        pendulum1_com=0.5,
        pendulum2_com=0.5,
        pendulum1_inertia=0.1,
        pendulum2_inertia=1e-12,    # force singularity
        gravity=9.81,
        cart_friction=0.1,
        joint1_friction=0.1,
        joint2_friction=0.1,
    )
    x = np.zeros(6)
    u = 0.0
    dt = 0.01
    x_next = step_rk4_numba(x, u, dt, p)
    assert np.any(np.isnan(x_next))

def test_pso_fitness_penalises_nan(monkeypatch):
    import src.optimization.algorithms.pso_optimizer as pso_mod
    
    def fake_simulate_system_batch(controller_factory, particles, sim_time, u_max=None):
        """
        Lightweight stand‑in for the real ``simulate_system_batch`` function used in
        PSOTuner tests.  The real implementation accepts an optional
        ``u_max`` parameter to bound the control input.  When monkeypatching
        this helper into the optimiser, ensure the signature matches the
        production API by including the ``u_max`` keyword argument with a
        default value.  This prevents a ``TypeError`` when PSOTuner
        forwards the control limit to the batch simulator.  The dummy
        implementation returns a deterministic set of trajectories with one
        trajectory containing a NaN to trigger the instability penalty logic.

        Parameters
        ----------
        controller_factory : callable
            Factory to create controllers (ignored here).
        particles : np.ndarray
            Array of particle gain vectors.
        sim_time : float
            Simulation horizon in seconds.
        u_max : float, optional
            Saturation limit for the control input.  Unused in this stub.

        Returns
        -------
        t : np.ndarray
            1D array of time points of length N+1.
        x_b : np.ndarray
            3D array of states shaped (B, N+1, 6).
        u_b : np.ndarray
            2D array of control inputs shaped (B, N).
        sigma_b : np.ndarray
            2D array of sliding variables shaped (B, N).
        """
        B, N = particles.shape[0], 5
        t = np.linspace(0, sim_time, N + 1)
        x_b = np.zeros((B, N + 1, 6))
        u_b = np.zeros((B, N))
        sigma_b = np.zeros((B, N))
        # Introduce a NaN for the first particle to simulate a failed trajectory
        x_b[0, 2, 0] = np.nan
        return t, x_b, u_b, sigma_b

    # Monkeypatch simulate_system_batch in the PSO optimizer module where it's used
    import src.optimization.algorithms.pso_optimizer as pso_optimizer_mod
    monkeypatch.setattr(pso_optimizer_mod, "simulate_system_batch", fake_simulate_system_batch, raising=True)

    # Create a minimal dummy configuration object for the PSO tuner.  The PSOTuner
    # only accesses the ``physics``, ``simulation``, ``cost_function``, and
    # optional ``physics_uncertainty`` attributes.  We avoid referencing
    # undefined classes like PSOConfig or CostFunction by constructing
    # simple stand-in objects.

    class DummyCost:
        """Simple cost configuration with required fields."""
        def __init__(self):
            # The weights object must have attributes used in PSOTuner
            self.weights = type("W", (), {
                "state_error": 1.0,
                "control_effort": 1.0,
                "control_rate": 1.0,
                "stability": 1.0,
            })()
            self.instability_penalty = 1e6

    class DummySim:
        """Simulation configuration exposing duration and dt."""
        duration = 1.0
        dt = 0.01

    class DummyCfg:
        def __init__(self):
            # Populate the physics configuration; PhysicsConfig comes from src.config
            self.physics = PhysicsConfig(
                cart_mass=1.0,
                pendulum1_mass=1.0,
                pendulum2_mass=1.0,
                pendulum1_length=1.0,
                pendulum2_length=1.0,
                pendulum1_com=0.5,
                pendulum2_com=0.5,
                pendulum1_inertia=0.1,
                pendulum2_inertia=0.1,
                gravity=9.81,
                cart_friction=0.0,
                joint1_friction=0.0,
                joint2_friction=0.0,
            )
            self.simulation = DummySim()
            self.cost_function = DummyCost()
            # Explicitly disable uncertainty; tuner will use only nominal physics
            self.physics_uncertainty = None

    dummy_cfg = DummyCfg()

    tuner = pso_mod.PSOTuner(
        controller_factory=lambda gains: type("C", (), {"max_force": 150.0})(),
        config=dummy_cfg
    )

    # Manually set normalization factors as they are set inside `optimise` normally
    tuner.norm_ise = 1.0
    tuner.norm_u = 1.0
    tuner.norm_du = 1.0
    tuner.norm_sigma = 1.0

    J = tuner._fitness(np.array([[1, 2, 3], [4, 5, 6]], float))
    
    assert J[0] == pytest.approx(tuner.instability_penalty)
    assert np.isfinite(J[1])
#=========================================================================================================================\\\
# END: test_full_dynamics.py

# BEGIN: test_model_comparison.py
#
"""
Test simplified vs. full dynamics model trajectories using shared fixtures.
"""

import pytest  # noqa: E402 - consolidated test file with multiple sections

# The test uses the shared 'dynamics' and 'full_dynamics' fixtures from conftest.py.
@pytest.mark.skip(reason="Fixture issue: physics_cfg contains singularity_cond_threshold field not accepted by SimplifiedDIPConfig - requires conftest.py fix")
def test_simplified_vs_full_model_error(dynamics, full_dynamics):
    """Simplified and full model trajectories should stay within tolerance."""
    # We'll simulate the simplified (dynamics) and full (full_dynamics) models using
    # a simple fixed-step integrator and zero control input. The goal is to ensure
    # that the trajectories of the two models stay close in the absence of control.
    x0 = np.array([0, np.pi / 6, np.pi / 6, 0, 0, 0], dtype=float)
    dt = 0.01
    sim_time = 5.0
    steps = int(np.round(sim_time / dt))
    # Preallocate arrays for the trajectories
    states_simple = np.zeros((steps + 1, x0.size), dtype=float)
    states_full = np.zeros((steps + 1, x0.size), dtype=float)
    states_simple[0] = x0
    states_full[0] = x0
    for k in range(steps):
        # Zero control input
        u = 0.0
        # For the simplified model (6D), call the dynamics.step method
        states_simple[k + 1] = dynamics.step(states_simple[k], u, dt)
        # For the full model (6D), call the full_dynamics.step method
        states_full[k + 1] = full_dynamics.step(states_full[k], u, dt)
    # Compute the norm of the difference between trajectories
    error_norm = np.linalg.norm(states_full - states_simple, axis=1)
    final_error = error_norm[-1]
    assert final_error < 5.0, (
        f"Final trajectory error norm is too large: {final_error:.4f}"
    )
 #   
# END: test_model_comparison.py

# BEGIN: test_dynamics_ill_conditioned.py
# tests/test_dynamics_ill_conditioned.py ==============================================================\\\
# A new test to verify that the dynamics model correctly handles ill-conditioned inertia matrices.
from src.core.dynamics import rhs_numba, DIPParams  # noqa: E402 - consolidated test file

@pytest.mark.skip(reason="Numba typing error with DIPParams - requires @jitclass decorator or refactoring")
def test_rhs_returns_nan_for_ill_conditioned_matrix():
    # Tiny m2/I2 -> near-singular inertia in certain poses
    p = DIPParams(
        cart_mass=1.0,
        pendulum1_mass=1.0,
        pendulum2_mass=1e-9,
        pendulum1_length=1.0,
        pendulum2_length=1.0,
        pendulum1_com=0.5,
        pendulum2_com=0.5,
        pendulum1_inertia=0.1,
        pendulum2_inertia=1e-12,
        gravity=9.81,
        cart_friction=0.1,
        joint1_friction=0.01,
        joint2_friction=0.01,
    )
    state = np.array([0.0, 0.1, -0.1, 0.0, 0.0, 0.0], dtype=np.float64)
    out = rhs_numba(state, 0.0, p)
    assert np.all(np.isnan(out)), "Expected NaNs for ill-conditioned inertia matrix"
#===================================================================================\\\    
# END: test_dynamics_ill_conditioned.py

# BEGIN: test_linalg_fix.py
# tests/test_linalg_fix.py ====================================================\\\

import pytest  # noqa: E402 - consolidated test file with multiple sections

@pytest.mark.skip(reason="Numba typing error with DIPParams - requires @jitclass decorator or refactoring")
def test_rhs_handles_singularity_gracefully():
    """
    Ensures that when the inertia matrix H is singular, the rhs_numba function
    returns an array of NaN values to signal the numerical failure, preventing
    silent data corruption.
    """
    # Create a set of parameters known to cause a singular H matrix
    # (e.g., a massless second pendulum)
    singular_params = DIPParams(
        cart_mass=1.0,
        pendulum1_mass=1.0,
        pendulum2_mass=1e-12,  # Effectively massless
        pendulum1_length=1.0,
        pendulum2_length=1.0,
        pendulum1_com=0.5,
        pendulum2_com=0.5,
        pendulum1_inertia=0.1,
        pendulum2_inertia=1e-12, # Effectively no inertia
        gravity=9.81,
        cart_friction=0.1,
        joint1_friction=0.01,
        joint2_friction=0.01,
    )

    # A state vector where the singularity might be encountered
    state = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0])
    u = 0.0

    # Execute the function that could fail
    xdot = rhs_numba(state, u, singular_params)

    # Assert that the output contains NaN values (the correct behavior)
    assert np.any(np.isnan(xdot)), "rhs_numba should return NaN values when the inertia matrix is singular"
    assert xdot.shape == (6,), "The output of rhs_numba has an incorrect shape"

    # Verify all elements are NaN (comprehensive failure signal)
    assert np.all(np.isnan(xdot)), "All elements should be NaN to clearly signal the failure"
#===========================================================================================================\\\   
# END: test_linalg_fix.py

# BEGIN: test_disturbance_boundary.py
# tests/test_disturbance_boundary.py =====================================================================\\\
def test_pulse_clamped_to_sim_end():
    sim_duration = 5.0
    d_start, d_dur, d_mag = 4.5, 1.0, 10.0
    def disturbance_function(time_now: float) -> float:
        window_end = min(d_start + d_dur, float(sim_duration))
        return float(d_mag) if (d_start <= time_now < window_end) else 0.0

    assert disturbance_function(4.49) == 0.0   # before start
    assert disturbance_function(4.50) == 10.0  # inside
    assert disturbance_function(4.99) == 10.0  # still inside
    assert disturbance_function(5.00) == 0.0   # at sim end → clamped off

 #========================================================================================================================================\\\   
# END: test_disturbance_boundary.py

